// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuwBKTTRmptPnUmaXs9Twx44Kq-Z0EqQ4',
    appId: '1:473501370378:web:f32c64fca535aa514337f3',
    messagingSenderId: '473501370378',
    projectId: 'mpati-84380',
    authDomain: 'mpati-84380.firebaseapp.com',
    databaseURL: 'https://mpati-84380-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mpati-84380.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCuR09j126lPb0HWCL9b-qi7Mq1u6JfE8',
    appId: '1:473501370378:android:ac95f1f55bf67e414337f3',
    messagingSenderId: '473501370378',
    projectId: 'mpati-84380',
    databaseURL: 'https://mpati-84380-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mpati-84380.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9p8FyeyVhAdfH2zeDpdygtI6Pp8Pkxco',
    appId: '1:473501370378:ios:6cec74f5cbba4bc74337f3',
    messagingSenderId: '473501370378',
    projectId: 'mpati-84380',
    databaseURL: 'https://mpati-84380-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mpati-84380.appspot.com',
    iosBundleId: 'com.example.mpatiPetCare',
  );
}
